---
title: "Problem Sets"
format: html
---

```{r, echo = F, message = F, warning = F}
library(tidyverse)
library(survival)
library(foreach)
```

Problem sets are currently posted on Piazza, but I plan to gather them on this page.

## Problem Set 1: Key Concepts

A study enrolls 6 people looking for work. 3 are randomly assigned to a job training intervention and 3 are randomly assigned to no job training. Over a 52-week follow-up period beginning January 1, the study records the time until they are hired in weeks.


| ID | Age | Treatment | Time until hired |
| --- | --- | --- | --- |
1 | 53 | Treated | 12 weeks |
2 | 26 | Treated | 10 weeks  |
3 | 37 | Treated | 44 weeks |
4 | 25 | Untreated | 7 weeks |
5 | 48 | Untreated | Never hired in 52 weeks |
6 | 34 | Untreated | 40 weeks |

1. What is time 0 in this study?
2. Which unit(s) were censored?
3. Can you point identify the mean time until hired in the treatment condition? If not, can you provide a lower bound? Ignore statistical uncertainty.
4. Can you point identify the mean time until hired in the untreated condition? If not, can you provide a lower bound? Ignore statistical uncertainty.
5. Does the job training reduce the average time until hired?

The next questions are about the Exponential distribution, which assumes a constant hazard: $h(t) = \lambda$.

6. True or False. The CDF $F(t) = P(T < t)$ is an increasing function of $t$.
7. True or False. The survival function $S(t) = P(T > t)$ is an increasing function of $t$.
8. A demographer studies a cohort of people born in 1965 where age is the time variable (with time zero at age zero). They study the time until first marriage. In 1--3 sentences, make an argument that the assumption of a constant hazard is implausible.

## Problem Set 2: Exponential

See the [exercise](exponential.qmd#exercise) at the end of the Exponential page.

## Problem Set 3: Weibull

This problem set practices Kaplan-Meier survival curve estimation and a Weibull model.

The `survival::veteran` data contain data from a clinical trial involving cancer patients run by the Veteran's Administration. These data are described in Kalbfleisch and Prentice (1980) on p.~60. There are 137 patients, and only 9 are censored before death. 

- `status` is 1 for death, 0 for censoring
- `time` is days of survival
- `trt` is a randomized chemotherapy test treatment. 1 indicates standard treatment, 2 indicates the test treatment

For more information on the data see `?survival::veteran`.

1. (10 points) Estimate survival curves by treatment status `trt`, using the Kaplan-Meier method. Visualize the results in a plot.
2. (10 points) Estimate survival curves by treatment status `trt`, using a Weibull regression with only this predictor. Visualize the results in a plot.
3. (10 points) Compare: Plot the Weibull and Kaplan-Meier survival curves on the same plot. How do they differ? For ease of comparison, you might use different panels or different plots for each treatment status so that it is easier to compare across models within treatment status.
4. (10 points) Plot the estimated Weibull hazard function. Does it increase or decrease with time?
5. (8 points) In your Weibull results, can you reject the null of an Exponential model?
6. (2 points, Challenge): Construct a confidence interval on each point of your Weibull survival functions and visualize the result. Note that this is quite challenging; it is only worth 2 points so that you can skip it and still get an A on the problem set. Here are some steps.
     - Define the X matrix at which to make predictions
     - Loop over simulations. In each iteration,
          - Simulate $\vec\beta$ and the `log_scale` parameter from a Multivariate Normal centered at `c(coef(model), log(model$scale))` with variance-covariance matrix `vcov(model)`
          - Calculate the simulated value of the `rweibull` parameter `scale`, which is $e^{\vec{X}'\vec\beta}$ where $\vec\beta$ are coefficients from `survreg`
          - Calculate the simulated value of the `rweibull` parameter `shape`, which is `1 / exp(log_scale)` where `log_scale` is the simulated value of the log of what `survreg` calls the scale parameter
          - Simulate survival functions with those parameters
     - At each point of the survival curve, calculate the 2.5 and 97.5 percentiles of the empirical distribution of simulated draws.
